### ISSUE TITLE
R estimation code

### ISSUE THREAD

**Issue by lrossouw** [mrc-ide/covid19-forecasts-orderly#6]
I checked this code base but would really like access to the Rt estimation code base for South Africa.  I'm assisting various parties and would love to produce these for those on a timely basis.  I think this code base only contains reporting/aggregation elements let me know if the Rt estimation code is available here?  

Your help would be appreciated.

Thanks
Louis

**Comment by sangeetabhatia03** [comment]
Hi, thanks for your interest in our work. We are using 3 different models to build an ensemble.
You can find the code for these models here: 
Model 1 - https://github.com/mrc-ide/covid19-forecasts-orderly/tree/main/src/I0Rtmodel
Model 2 - https://github.com/sangeetabhatia03/projections2020
Model 3 - https://github.com/mrc-ide/covid19-forecasts-orderly/tree/main/src/DeCa_model
Model 3 uses code packaged up here: https://github.com/sangeetabhatia03/ascertainr

Note that we are working on better organising the code for Model 1. Rt estimation happens within each model. If you are only interested in extracting estimates for S Africa, we also publish model outputs as a release associated with this repo each week. Hope this helps!

**Comment by seabbs** [comment]
Hi @sangeetabhatia03, 

Just to note that I would be very interested in exploring some of these approaches in more detail if/when they get pulled out as reusable pieces of code (appreciate this may not be the current focus).
